### PR TITLE
Introduce annotation based suppressions

### PR DESCRIPTION
**Pull request by f1ames**
This PR introduces annotation based suppressions. Fixes https://github.com/kubeshop/monokle-saas/issues/2309.

## Changes

- Introduced quick fix actions to suppress violated rules.
- Created abstract `CodeActionProvider` class which can be reused for different types of actions (other types of suppressions, autofixes, etc).

## Fixes

- None.

## How it works

monokle 20240124-1

## Remarks

1. As you can see on the gif above, suppressed violations are marked as `Suppressed` in violations panel only. There is still highlight for them and are shown in problems panel. This is quite confusing and there is dedicated issue to fix this - https://github.com/kubeshop/vscode-monokle/issues/78.
2. Sometimes one suppression would fix multiple violation (for same rule, like recommended labels). I think it doesn't make sense to put separate action for each single violation just for the rule itself (as shown above).
3. I used an annotation format like `monokle.io/suppress.ruleId: suppress` because using boolean `true` violates schema resulting in `K8S001` violation 😅 
4. The above and quick fix labels to discuss. We can change wording there if we find better alternatives.
5. I saw that in the cloud we select new changes applied to resource (for autofixes). From what I tested with qucikfixes from different VSC plugins, the selection stays untouched so I went with the same approach to not change it.
6. Left one [`@TODO`](https://github.com/kubeshop/vscode-monokle/pull/87/files#diff-1eee0ade1de545be631f4bb1f9136331cd2992b2da7a09f06f7144a791fcac29R82-R86) in the code on purpose. It's not needed for this PR but will be needed for others.

## Checklist

- [x] tested locally
- [x] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Comment by WitoDelnat** [comment]
Awesome work!

For the annotation key, I believe we should rely more on the human-readable form (monokle.io/suppress.kbp.no-latest-image) over the rule identifier form (monokle.io/suppress.KBP007). When you have multiple suppressions, it's hard to understand what the latter is now actually suppressing.

For the annotation value, it's indeed a petty limitation that you cannot use `true` due to the JSON Schema as it makes more sense. I see [Traefik](https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/) uses `"true"` which might be a possibility. For full context, the original intention was that if you provide a string, it's to be added as the SARIF suppression's justification (e.g. `"won't fix"` or `"false positive"`). I think for a quick action it's to complicated to give a selection / input for justifications.

**Review by WitoDelnat — APPROVED** [review]

**Review by WitoDelnat — CHANGES_REQUESTED** [review]
Code itself looks good. There is the comment I left about the annotation key-value that we should still change imho.

**Comment by f1ames** [comment]
Thanks for feedback @WitoDelnat. Changed to use full rule name for annotations [e55dd7f](https://github.com/kubeshop/vscode-monokle/pull/87/commits/e55dd7f0470621517162e2cdb3d7972fbd0fca6e) and also added telemetry [c0c9490](https://github.com/kubeshop/vscode-monokle/pull/87/commits/c0c9490e3dd540e1243d82c88b5d2661eb6298f0).

**Comment by WitoDelnat** [comment]
> Maybe good way to tackle this would be mentioning in the docs/readme that one can change annotation value as it acts as justification comment

That's definitely a good place for it! Feel free to do that.

**Pull request merged**
